// This file will be auto-generated by Supabase CLI
// Run: npm run generate-types
// For now, using a minimal type definition

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          first_name: string
          last_name: string
          phone: string | null
          profile_picture_url: string | null
          faculty: string | null
          specialization: string | null
          year: number | null
          program_type: 'LICENSE' | 'MASTER' | 'DOCTORAT' | null
          role: 'STUDENT' | 'PROFESSOR' | 'ADMIN'
          is_active: boolean
          email_verified: boolean
          last_login: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id: string
          email: string
          first_name: string
          last_name: string
          phone?: string | null
          profile_picture_url?: string | null
          faculty?: string | null
          specialization?: string | null
          year?: number | null
          program_type?: 'LICENSE' | 'MASTER' | 'DOCTORAT' | null
          role?: 'STUDENT' | 'PROFESSOR' | 'ADMIN'
          is_active?: boolean
          email_verified?: boolean
          last_login?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          email?: string
          first_name?: string
          last_name?: string
          phone?: string | null
          profile_picture_url?: string | null
          faculty?: string | null
          specialization?: string | null
          year?: number | null
          program_type?: 'LICENSE' | 'MASTER' | 'DOCTORAT' | null
          role?: 'STUDENT' | 'PROFESSOR' | 'ADMIN'
          is_active?: boolean
          email_verified?: boolean
          last_login?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
      }
      // Add other tables here as we build them
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
